// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajrcdmxznlhyervttmea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcmNkbXh6bmxoeWVydnR0bWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjE3ODIsImV4cCI6MjA2NDQ5Nzc4Mn0.JcLDDl2zd0LqEX0HJRAauwLziPgfUqsn4UVwxpnHIYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);